### ISSUE TITLE
Captain hook plugin

### ISSUE THREAD

**Issue by SamMousa** [ramsey/conventional-commits#30]
The README mentions a Captain hook plugin, but the `composer.json` lists CaptainHook as a dependency.

I think either the README should reflect the CaptainHook library is a hard dependency, or it should be listed as a suggested dependency instead.

Let me know if you agree and I'll implement a PR. Personally I think, if possible, it would be best to list CaptainHook as an optional dependency.

**Comment by SamMousa** [comment]
Will you do it or should i make a PR?

**Comment by ramsey** [comment]
Feel free to make a PR, if you like. Otherwise, I'll try to get to this soon. Thanks!

**Comment by ramsey** [comment]
Thanks for the suggestion. I released this in version 1.3.0.
