### ISSUE TITLE
Allow failure for PHPStan?

### ISSUE THREAD

**Issue by Lewiscowles1986** [ramsey/conventional-commits#33]
In my recent PR #31 it seems stan vomited. If the repo is not yet ready, perhaps PHPStan could be configured to report only; or `continue-on-error` for that step could be set to `true`?

## Example code

`continue-on-error: true`

## Alternative solutions:

I Could PR after running locally with `--generate-baseline`, so that this never should get worse; but existing errors I think get ignored.

**Comment by ramsey** [comment]
If you have a repo you don't make changes to for a few months, while PHPStan undergoes many changes, then when you run  `composer update` and try to run static analysis, you get tons of errors. 🤦🏻‍♂️ 

This is annoying, but it's the reality of working with these tools. The repo had everything in place correctly, but changes to the tools over time caused these failures. Sorry.
