### ISSUE TITLE
Add this library in conventionalcommits.org.

### ISSUE THREAD

**Issue by cocoeyes02** [ramsey/conventional-commits#44]
## My feature title
Add this library in conventionalcommits.org.

## Background/problem

I want many people to use this library.
If this library's name's written in conventionalcommits.org, more many people can know and use this library.
https://www.conventionalcommits.org/

## Proposal/solution

In about page, add this library's name and description to `Tooling for Conventional Commits`
https://www.conventionalcommits.org/en/about/

For example...
* [conventional-commits](https://github.com/ramsey/conventional-commits): A PHP library for creating and validating commit messages according to the Conventional Commits specification.

https://github.com/conventional-commits/conventionalcommits.org/pull/434

**Comment by ramsey** [comment]
Thanks! This looks good to me.

**Comment by cocoeyes02** [comment]
PR merged and add this library's name and description in conventionalcommits.org. 🎉 
I hope more many people know and use this library!
