### ISSUE TITLE
When will a new version be available with the validate command

### ISSUE THREAD

**Issue by toniop99** [ramsey/conventional-commits#67]
Just wanna know when the new command added a weeks ago for validate a msg will be available.

**Comment by ecourtial** [comment]
Yes that strange because it is still mentioned in the documentation.
What is the issue? The feature is completely removed or it is just temporary?
If so, need any help to put it back?

**Comment by ramsey** [comment]
@ecourtial The README document in the main branch is showing details for an unreleased version. I need to release it. 😄 

I'll try to release the new version soon. Thanks!

**Comment by ecourtial** [comment]
Thanks for the heads-up :) !

**Comment by ramsey** [comment]
Sorry for the delay! Version 1.4.0 is now out with the `validate` command. /cc @hussainweb
